#!/bin/bash	
python describe_neurons.py --target_model "resnet" --target_layer "resnet.embedder, resnet.encoder.stages[0],resnet.encoder.stages[1],resnet.encoder.stages[2],resnet.encoder.stages[3]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 
python describe_neurons.py --target_model "resnet-cub" --target_layer "resnet.embedder, resnet.encoder.stages[0],resnet.encoder.stages[1],resnet.encoder.stages[2],resnet.encoder.stages[3]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 
python describe_neurons.py --target_model "resnet-bloodmnist" --target_layer "resnet.embedder, resnet.encoder.stages[0],resnet.encoder.stages[1],resnet.encoder.stages[2],resnet.encoder.stages[3]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 

python describe_neurons.py --target_model "vit" --target_layer "vit.encoder.layer[0],vit.encoder.layer[1],vit.encoder.layer[2],vit.encoder.layer[3],vit.encoder.layer[4],vit.encoder.layer[5],vit.encoder.layer[6],vit.encoder.layer[7],vit.encoder.layer[8],vit.encoder.layer[9],vit.encoder.layer[10],vit.encoder.layer[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 
python describe_neurons.py --target_model "vit-cub" --target_layer "vit.encoder.layer[0],vit.encoder.layer[1],vit.encoder.layer[2],vit.encoder.layer[3],vit.encoder.layer[4],vit.encoder.layer[5],vit.encoder.layer[6],vit.encoder.layer[7],vit.encoder.layer[8],vit.encoder.layer[9],vit.encoder.layer[10],vit.encoder.layer[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 
python describe_neurons.py --target_model "vit-bloodmnist" --target_layer "vit.encoder.layer[0],vit.encoder.layer[1],vit.encoder.layer[2],vit.encoder.layer[3],vit.encoder.layer[4],vit.encoder.layer[5],vit.encoder.layer[6],vit.encoder.layer[7],vit.encoder.layer[8],vit.encoder.layer[9],vit.encoder.layer[10],vit.encoder.layer[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 

python describe_neurons.py --target_model "dino" --target_layer "dinov2.encoder.layer[0],dinov2.encoder.layer[1],dinov2.encoder.layer[2],dinov2.encoder.layer[3],dinov2.encoder.layer[4],dinov2.encoder.layer[5],dinov2.encoder.layer[6],dinov2.encoder.layer[7],dinov2.encoder.layer[8],dinov2.encoder.layer[9],dinov2.encoder.layer[10],dinov2.encoder.layer[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 
python describe_neurons.py --target_model "dino-cub" --target_layer "dinov2.encoder.layer[0],dinov2.encoder.layer[1],dinov2.encoder.layer[2],dinov2.encoder.layer[3],dinov2.encoder.layer[4],dinov2.encoder.layer[5],dinov2.encoder.layer[6],dinov2.encoder.layer[7],dinov2.encoder.layer[8],dinov2.encoder.layer[9],dinov2.encoder.layer[10],dinov2.encoder.layer[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 
python describe_neurons.py --target_model "dino-bloodmnist" --target_layer "dinov2.encoder.layer[0],dinov2.encoder.layer[1],dinov2.encoder.layer[2],dinov2.encoder.layer[3],dinov2.encoder.layer[4],dinov2.encoder.layer[5],dinov2.encoder.layer[6],dinov2.encoder.layer[7],dinov2.encoder.layer[8],dinov2.encoder.layer[9],dinov2.encoder.layer[10],dinov2.encoder.layer[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 

python describe_neurons.py --target_model "clip" --target_layer "vision_model.encoder.layers[0],vision_model.encoder.layers[1],vision_model.encoder.layers[2],vision_model.encoder.layers[3],vision_model.encoder.layers[4],vision_model.encoder.layers[5],vision_model.encoder.layers[6],vision_model.encoder.layers[7],vision_model.encoder.layers[8],vision_model.encoder.layers[9],vision_model.encoder.layers[10],vision_model.encoder.layers[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 
python describe_neurons.py --target_model "clip-cub" --target_layer "vision_model.encoder.layers[0],vision_model.encoder.layers[1],vision_model.encoder.layers[2],vision_model.encoder.layers[3],vision_model.encoder.layers[4],vision_model.encoder.layers[5],vision_model.encoder.layers[6],vision_model.encoder.layers[7],vision_model.encoder.layers[8],vision_model.encoder.layers[9],vision_model.encoder.layers[10],vision_model.encoder.layers[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 
python describe_neurons.py --target_model "clip-bloodmnist" --target_layer "vision_model.encoder.layers[0],vision_model.encoder.layers[1],vision_model.encoder.layers[2],vision_model.encoder.layers[3],vision_model.encoder.layers[4],vision_model.encoder.layers[5],vision_model.encoder.layers[6],vision_model.encoder.layers[7],vision_model.encoder.layers[8],vision_model.encoder.layers[9],vision_model.encoder.layers[10],vision_model.encoder.layers[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 

python describe_neurons.py --target_model "mae" --target_layer "vit.encoder.layer[0],vit.encoder.layer[1],vit.encoder.layer[2],vit.encoder.layer[3],vit.encoder.layer[4],vit.encoder.layer[5],vit.encoder.layer[6],vit.encoder.layer[7],vit.encoder.layer[8],vit.encoder.layer[9],vit.encoder.layer[10],vit.encoder.layer[11]" --d_probe "imagenet_broden" --concept_set "data/20k.txt" 



